### PR TITLE
Update slovakia.md

### PR DESCRIPTION
**Pull request by miro41**
TV channels did not works, wrong URLs were there, I fix it.

### CODE REVIEW

**Comment by KAMI911** [comment]
Thanks

**Comment by VlastikYoutubeKo** [comment]
@miro41 Hi, what do you mean "did not works"?
The urls were working, you just put there homepages of the televisions...

**Comment by VlastikYoutubeKo** [comment]
[Proof](https://amz.odjezdy.online/xbackbone/VUne9/deGihIxI55.mp4)

**Comment by VlastikYoutubeKo** [comment]
@KAMI911 please check the URLs next time, you allowed urls of homepages, not stream URLs 😆

**Pull request merged**
