### PR TITLE
Update germany.md

### PR DESCRIPTION
**Pull request by telluroid**
add music tv channels, numbering per section

### CODE REVIEW

**Comment by telluroid** [comment]
I fixed the conflict, @KAMI911

**Comment by telluroid** [comment]
@KAMI911 Any reason this does not get merged? What can I improve?

**Comment by KAMI911** [comment]
Thank you, I just did not realized that you fixed it, sorry. Now I merged.

**Comment by telluroid** [comment]
Thank you. Unfortunately I just realized that they closed down two channels in the mean time. I will open a new request to remove them.

**Pull request merged**
