### PR TITLE
[italy.md] updated channels

### PR DESCRIPTION
**Pull request by Brenders**

### CODE REVIEW

**Comment by KAMI911** [comment]
Thank you for the update!

**Comment by Brenders** [comment]
ok i need fix last push i think

**Comment by KAMI911** [comment]
I just added EPG ids with last merge. Could you also add them? They are in last columns. Thank you in advance!

**Comment by Brenders** [comment]
you can also delete this duplicate channels

```
#EXTINF:-1 tvg-name="Rtv Calabria" tvg-logo="https://i.imgur.com/Ytwyx8D.png" group-title="Italy",Rtv Calabria
https://59d7d6f47d7fc.streamlock.net/reggiotv/reggiotv/playlist.m3u8
#EXTINF:-1 tvg-name="Tva Agrigento" tvg-logo="https://i.imgur.com/6dxp79F.png" group-title="Italy",Tva Agrigento
https://59d7d6f47d7fc.streamlock.net/tva/tva/playlist.m3u8
```

**Comment by Brenders** [comment]
i have push fix

**Pull request closed without merging**
