### PR TITLE
Update italy.md

### PR DESCRIPTION
**Pull request by dioraman**
The channel named "Byoblu Tv" breaches the policy "No channels dedicated to any particular political party".
Claudio Messora, Byoblu Tv sole proprietor and editor-in-chief, runs for a seat in the Italian Lower Chamber / Parlamento. [[0](https://www.ideawebtv.it/2022/08/04/elezioni-italia-sovrana-e-popolare-presenta-i-candidati-in-granda-porteremo-le-istanze-dei-cittadini-in-parlamento-video/)][[1](https://www.ildolomiti.it/politica/2022/dal-fondatore-di-byoblu-a-marco-rizzo-fino-ad-ingroia-ecco-chi-sono-i-candidati-trentini-per-la-lista-no-vax-anti-ue-e-anti-nato)][[2](https://www.ildenaro.it/elezioni-italia-sovrana-e-popolare-dalla-lollo-a-fulvio-grimaldi-candidati-in-tuttitalia/)][[3](https://www.torinotoday.it/politica/elezioni-politiche-25-settembre-2022/candidati-italia-sovrana-popolare-camera-senato.html)][[4](https://www.ideawebtv.it/2022/08/25/italia-sovrana-e-popolare-ammessa-alle-elezioni-ufficiali-i-candidati-cuneesi-per-camera-e-senato/)]

More broadly, Byoblu Edizioni Srls is as organization that promotes content that incites violence or hatred towards a person or group of people based on race, religion, gender identity or expression, sex, ethnicity, nationality, sexual orientation, etc., and content that promotes dangerous false or dangerous deceptive medical information that may cause offline harm or poses a direct threat to public health.

### CODE REVIEW

**Comment by NezbednikSK** [comment]
!

**Comment by Brenders** [comment]
> The channel named "Byoblu Tv" breaches the policy "No channels dedicated to any particular political party"

if you have to follow this rule to the letter, there shouldn't be all the mediaset channels because they are Berlusconi = political right, some regional channels and some other main channels that are political left, etc. . You can understand that the channels are digital terrestrial and in this case you try to make all the channels available then it is up to you to see them or not because you do not agree with the party or otherwise.

> 
> More broadly, Byoblu Edizioni Srls is as organization that promotes content that incites violence or hatred towards a person or group of people based on race, religion, gender identity or expression, sex, ethnicity, nationality, sexual orientation, etc., and content that promotes dangerous false or dangerous deceptive medical information that may cause offline harm or poses a direct threat to public health.

I hope that the part you wrote below is not a defamation ... I move away in this case, also because in Italy such a thing is not allowed and the police would certainly intervene since the channel is normally accessible on TV. Are you sure what you wrote?

**Comment by NezbednikSK** [comment]
@Brenders shall this be reverted?

**Comment by Brenders** [comment]
> @Brenders shall this be reverted?

in my opinion yes, also because we have in the list of the main digital terrestrial channels belonging to politicians currently in office, before we also had state channels (RAI channels) I have to try to fix them.

**Comment by dioraman** [comment]
Please give me the opportunity to elaborate.

**Comment by Brenders** [comment]
I state that the facts you wrote seemed so serious to me that I believed they were defamations, I still can't believe it 😲, if what you wrote is real I would also agree not to keep the channel in the list, you could attach some article in which you talk about what you wrote? so as to inform me even better about everything.

**Comment by Brenders** [comment]
I state that the facts you wrote seemed so serious to me that I believed they were defamations, I still can't believe it 😲, if what you wrote is real I would also agree not to keep the channel in the list, you could attach some article in which you talk about what you wrote? so as to inform me even better about everything.

**Comment by dioraman** [comment]
I am just a random user who found that channel in the list. As International resource, you might consider the following:
[[0](https://www.newsguardtech.com/wp-content/uploads/2021/04/Twitter-Report-April-20-2021.pdf)] (page 8, English) & [[1](https://www.newsguardtech.com/wp-content/uploads/2022/03/ByoBlu-20220318.pdf)] (Italian).

Random order:

- the sole proprietor and editor-in-chief delivers anti-Semitic & Islamophobic content, *e.g.* having prime-timed [[2](https://www.la7.it/la-gabbia/video/claudio-messora-e-il-piano-kalergi-24-09-2015-163057)] neo-Nazi Honsik's "Kalergi plan" conspiracy theory. [[3](https://en.wikipedia.org/wiki/Kalergi_Plan)]
- the channel transmitted OVALmedia's movie "CORONA.film prologue", which on turn has already been removed from Vimeo and Youtube. OVALmedia is reknown for its conspiracy theory productions. [[4](https://www.tagesspiegel.de/themen/reportage/kampagne-gegen-tagesspiegel-die-verschwoerungsmaerchen-die-ovalmedia-verbreitet/27024684.html)]
- the company publishes Citro della Riva's book "Eresia" ["Heresy"], which entered weekly bestseller list in Italy and named
"anti-vaxx Bible" not surprisingly. Incipit: *«Covid can be treated simply with hydroxychloroquine also via aerosol, cortisone, zinc, vitamin C (best IV), vitamin D3. And prevented with "proper diet". A correlation is made between the 5G and the spread of the virus, it is implied that the coronavirus was born in the lab in Wuhan, maybe due to human error or who knows, only that "the System protects the lie"».* [[5](https://www.repubblica.it/politica/2021/08/31/news/eresia_bestseller_bibbia_no_covid-315924076/)][[6](https://www.open.online/2021/09/01/covid-19-massimo-citro-eresia-libro/)][[7](https://www.rollingstone.it/politica/come-un-libro-complottista-e-negazionista-del-covid-e-diventato-un-bestseller-in-italia/580406/)][[8](https://www.ilfoglio.it/lettere/2021/09/07/news/euro-bilderberg-11-9-il-cialtro-complottismo-e-sempre-lo-stesso-2872878/)]
- the channel promotes supremacist conspiracy fantasies, often with a transphobic/misoginist *e.g.* the "gender ideology plot" [[9](https://en.wikipedia.org/wiki/Anti-gender_movement)].

This is just scratching the surface. I acknowledge the sources I am using are often liberal-leaning, particularly NewsguardTech which is a for-profit tech company. I leave to the readers whether considering their reports enough accountable.

**Comment by Brenders** [comment]
Thank you @dioraman for illustrating everything, I am still shocked at how it is possible to have such a channel on TV. You did well to remove the channel, being a "regional" channel I did not inquire and I did not know all these things, when you indicated the removal of the channel for political reasons I could not understand, you were wrong to indicate the reason, I will try to speak with @NezbednikSK to introduce a ban on channels that publish fake news.

NezbednikSK this pull request is fine I understand the reason why the channel was removed and I agree with dioraman choice.

**Comment by NezbednikSK** [comment]
i'm not the one who maintains this, ask @freetv332 for that

**Pull request merged**
