### PR TITLE
Update French channels

### PR DESCRIPTION
**Pull request by TVKaista**

### CODE REVIEW

**Comment by jarbowski** [comment]
Cnews stream URL is https://www.dailymotion.com/video/x3b68jn

**Comment by KAMI911** [comment]
What is the status of this issue?

**Comment by jarbowski** [comment]
Still not resolved :
This URL doesn't work in VLC nor Hypnotix https://www.dailymotion.com/video/x3b68jn
And this URL just works https://www.dailymotion.com/video/x3b68jn

**Comment by KAMI911** [comment]
Thank you!

**Pull request merged**
