### PR TITLE
add rsi channel to switzerland.md

### PR DESCRIPTION
**Pull request by Brenders**
add rsi channel to switzerland.md

### CODE REVIEW

**Comment by Brenders** [comment]
@infid0 remember to update .m3u file

**Comment by infid0** [comment]
@Brenders Sorry i'm a newbie and i don't want made some trouble. But @KAMI911 is an expert. I hope he help us. :3

**Comment by KAMI911** [comment]
Regenerated the playlist with [d797e87](https://github.com/Free-TV/IPTV/commit/d797e87f041ad37dfb8b84cd96d9ac6c353482ee) commit.

**Comment by infid0** [comment]
> Regenerated the playlist with [d797e87](https://github.com/Free-TV/IPTV/commit/d797e87f041ad37dfb8b84cd96d9ac6c353482ee) commit.

Thank you so much! :3

**Pull request merged**
