### PR TITLE
Add Finnish channels

### PR DESCRIPTION
**Pull request by TVKaista**
Not sure if the epg ids are correct

Alfatv is discontinued

### CODE REVIEW

**Comment by TVKaista** [comment]
TLC is an American cable TV network, but its' Finnish edition is a free-to-air channel in Finland.

List of Finnish free-to-air channels can be found from Digita's website:
https://www.digita.fi/verkkojen-saatavuus/antennitvn-kartta-ja-saatavuus/

The green ones are unencrypted.

**Comment by TVKaista** [comment]
TLC is an American cable TV network, but its' Finnish edition is a free-to-air channel in Finland.

List of Finnish free-to-air channels can be found from Digita's website:
https://www.digita.fi/verkkojen-saatavuus/antennitvn-kartta-ja-saatavuus/

The green ones are unencrypted.

**Comment by TVKaista** [comment]
None that I am aware of.

Most non-Yle free-to-air channels in Finland are not available for Internet livestream. They are however available in terrestial DVB-T unencrypted.

For example Nelonenmedia's free-to-air channels (Nelonen, Liv, Jim) are available in Ruutu.fi service, but requires authentication and geoblocks IP addresses outside Finland.

**Comment by TVKaista** [comment]
Any updates?

I think this should be approved because it fits into the free channels (via DVB-T)

>Only channels which are officially provided for free (via DVB-S, DVB-T, analog, etc..)

**Comment by KAMI911** [comment]
If illegal then not. If free to air then probably yes.

**Comment by KAMI911** [comment]
Only free channels

If a channel is normally only available via commercial subscriptions it has nothing to do in this playlist. If on the other hand it is provided for free to everybody in a particular country, then it should be in this playlist.

    No paid channels
    Only channels which are officially provided for free (via DVB-S, DVB-T, analog, etc..)

**Pull request merged**
