### PR TITLE
Add initial list of free Hungarian channels

### PR DESCRIPTION
**Pull request by KAMI911**

### CODE REVIEW

**Comment by NezbednikSK** [comment]
some of the channels are georestricted (tested with hungarian proxy) and if i remember Spektrum Home is not FTA...?

**Comment by KAMI911** [comment]
According to [Antenna Hungaria homepage](https://www.ahrt.hu/hu/mindigtv) these are the DVB-T channels:

- M1 HD
- M2 HD
- Duna HD
- M4 Sport
- M5 HD
- Duna World HD
- RTL Klub
- TV2
- Izaura TV
- Spektrum Home
- Dikh TV
- Pesti TV
They are FTA, so we can reach them without any restriction.

**Comment by KAMI911** [comment]
Which are georestricted? How should we handle those situation?

**Comment by NezbednikSK** [comment]
strange, when i navigate to the official site, it lets me play the stream, but the links in your playlist are geoblocked..?

**Comment by KAMI911** [comment]
Could you @NezbednikSK merge the this PR? I think it is a good starter set of Hungarian TV channels.

**Comment by NezbednikSK** [comment]
i'm not the admin here, and it's been stale for long

**Comment by KAMI911** [comment]
@freetv332 could you merge this?

**Pull request merged**
