### PR TITLE
More czech and slovak channels

### PR DESCRIPTION
**Pull request by NezbednikSK**
The Prima channels, you need to be in Czechia. I used a proxy, but it works fine.

### CODE REVIEW

**Comment by NezbednikSK** [comment]
*i tested by setting http_proxy and using mpv

**Comment by NezbednikSK** [comment]
And also credit to iptv-org for the method of the Nova URLs that also can be applied to the Prima ones.

**Comment by NezbednikSK** [comment]
And the URLs are sourced from (with a little editing, see above)
https://novaplus.nova.cz/sledujte-zive/1-nova
https://www.iprima.cz/

Both geoblocked!

**Comment by infid0** [comment]
@NezbednikSK Sorry for the Off Topic, but you can test these public channel from Slovakia? 

| 1   | :1 (Jednotka) Ⓖ | [>](https://n0.stv.livebox.sk/stv-tv/_definst_/stv1.smil/playlist.m3u8) |  |
| 2   | :2 (Dvojka) Ⓖ  | [>](https://n0.stv.livebox.sk/stv-tv/_definst_/stv2.smil/playlist.m3u8) |  |
| 3   | :3 (Trojka) Ⓖ  | [>](https://n0.stv.livebox.sk/stv-tv/_definst_/stv3.smil/playlist.m3u8) |  |
| 4   | :O Ⓖ           | [>](https://n0.stv.livebox.sk/stv-tv/_definst_/stv6.smil/playlist.m3u8) |  |
| 5   | RTVS Ⓖ         | [>](https://n0.stv.livebox.sk/stv-tv/_definst_/stv5.smil/playlist.m3u8) |  |
| 6   | NR SR Ⓖ        | [>](https://n0.stv.livebox.sk/stv-tv/_definst_/stv7.smil/playlist.m3u8) |  |

If works, please put these channels in slovakia list. Thank you so much! :3

**Comment by NezbednikSK** [comment]
> @NezbednikSK Sorry for the Off Topic, but you can test these public channel from Slovakia?
> 
> | 1 | :1 (Jednotka) Ⓖ | > | |
> | 2 | :2 (Dvojka) Ⓖ | > | |
> | 3 | :3 (Trojka) Ⓖ | > | |
> | 4 | :O Ⓖ | > | |
> | 5 | RTVS Ⓖ | > | |
> | 6 | NR SR Ⓖ | > | |
> 
> If works, please put these channels in slovakia list. Thank you so much! :3

Yeah, they don't. All of those use dynamic URLs. However I have a forwarder for them, if that helps.

**Comment by NezbednikSK** [comment]
image
(Translation: "Warning", "Broadcast was stopped because of inactivity, please refresh the page.")

**Comment by infid0** [comment]
> Yeah, they don't. All of those use dynamic URLs. However I have a forwarder for them, if that helps.

Ok, thank you so much for testing! :3

**Comment by NezbednikSK** [comment]
Now, let me reverse this :)
Can you try opening up mpv with `https://runkit.io/nezbednik/yoink-that-stv/branches/master/?x=1`?

**Comment by infid0** [comment]
> 
> 
> Now, let me reverse this :)
> Can you try opening up mpv with `https://runkit.io/nezbednik/yoink-that-stv/branches/master/?x=1`?

Sorry, not work for me, but i'm from Italy.
vlcsnap-2021-07-16-15h12m08s190

**Comment by NezbednikSK** [comment]
That's fantastic! That is shown when a program they are not allowed to play online is broadcasted on TV. So it works outside Slovakia, nice.

**Comment by infid0** [comment]
Well, it's a good news! :D

**Comment by NezbednikSK** [comment]
Slovak channels sourced from
https://www.rtvs.sk/
https://videoarchiv.markiza.sk/live/1-markiza (with some more URL editing, inspired by the main Nova channel)

**Comment by Mirekbfive** [comment]
Zdravím .
mužete mi někdo pomoc s url pro pořady TV NOVA, NOVA GOLD atd. pro aplikaci FERMATA? kanály jako je prima jdou bez problemu . dekuji moc

**Comment by Mirekbfive** [comment]
ahoj vubec tomu nerozumim ....ale kanaly jako je JOJ nebo u nas PRIMA
normalne fungujr dobře

po 27. 3. 2023 v 18:51 odesílatel NezbednikSK ***@***.***>
napsal:

**Comment by Mirekbfive** [comment]
Umíš to nějak převést

Dne po 27. 3. 2023 18:51 uživatel NezbednikSK ***@***.***>
napsal:

**Comment by Mirekbfive** [comment]
Zdravím pán nezbednik.som tiež z Sk môžeme si napísať na fb
https://www.facebook.com/robo.kovac.3

Dňa po 27. 3. 2023, 20:32 Miroslav Folk ***@***.***> napísal(a):

**Pull request merged**
